name: mobile_ui_kit_ecommerce_community
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFA451"
  android: true
  ios: true
  android_12:
    color: "#FFA451"
    icon_background_color: "#FFA451"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:

    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/Brandon Grotesque Bold.ttf